import type { ClientConfig } from "@/types/client";

/**
 * Client registry (V1 local data source).
 *
 * To onboard a new business, add a ClientConfig object below — no UI changes
 * are required. Visiting /<slug> will render the fully branded app.
 * Later this array can be replaced by Firebase/Supabase/REST in clientService.
 *
 * All social/Google URLs for demo clients are safe placeholders.
 */
export const clients: ClientConfig[] = [
  {
    id: "client_bake",
    source: "local",
    slug: "bake",
    businessName: "BAKE Café & Bakery",
    displayName: "BAKE",
    displaySubtitle: "CAFÉ & BAKERY",
    logo: "/clients/bake/logo.svg",
    favicon: "/clients/bake/logo.svg",
    tagline: "Good Food — Brighter Days",
    description: "Share your experience, view our menu, earn loyalty stamps and more at BAKE Café & Bakery.",
    currency: "₹",
    theme: {
      primary: "#4a2c18",
      primaryDark: "#3a2111",
      secondary: "#f6eddd",
      accent: "#e3a43a",
      onAccent: "#2e1a0d",
      background: "#faf4ea",
      surface: "#fffaf2",
      text: "#4a2c18",
      muted: "#8a6a4d",
      borderRadius: "1rem",
    },
    coverImage: "/clients/bake/cover.jpg",
    googleReviewUrl: "https://search.google.com/local/writereview?placeid=demo-bake-cafe",
    socialLinks: {
      instagram: "https://www.instagram.com/bakecafe.demo",
      facebook: "https://www.facebook.com/bakecafe.demo",
      youtube: "https://www.youtube.com/@bakecafe.demo",
      website: "https://bake.example.com",
    },
    wifi: { enabled: true, ssid: "BAKE_GUEST", hint: "Enjoy fast & free internet while you're here!" },
    loyalty: { enabled: true, stampTarget: 8, rewardName: "Free Coffee" },
    aiReview: { enabled: true, monthlyLimit: 300 },
    menuCategories: ["Coffee", "Sandwich", "Pastry", "Cake", "Cookie"],
    menu: [
      { id: "cappuccino", name: "Cappuccino", description: "Rich espresso topped with velvety steamed milk foam.", price: 180, category: "Coffee", image: "/clients/bake/cappuccino.jpg", emoji: "☕", rating: 5, ingredients: ["Espresso", "Steamed milk", "Milk foam"], dietaryInfo: ["Vegetarian"], allergens: ["Dairy"], preparationTime: "4 min", calories: 120, featured: true },
      { id: "cold-coffee", name: "Cold Coffee", description: "Chilled blended coffee with milk and a hint of cocoa.", price: 160, category: "Coffee", image: "/clients/bake/cold-coffee.jpg", emoji: "🥤", rating: 4, ingredients: ["Espresso", "Chilled milk", "Ice", "Cocoa"], dietaryInfo: ["Vegetarian"], allergens: ["Dairy"], preparationTime: "5 min", calories: 210 },
      { id: "latte", name: "Caffè Latte", description: "Smooth espresso with silky steamed milk and light foam.", price: 190, category: "Coffee", image: "/clients/bake/cappuccino.jpg", emoji: "☕", rating: 5, ingredients: ["Espresso", "Steamed milk", "Light foam"], allergens: ["Dairy"], preparationTime: "4 min" },
      { id: "veg-sandwich", name: "Veg Sandwich", description: "Grilled garden veggies with herbed cheese on toasted bread.", price: 220, category: "Sandwich", image: "/clients/bake/veg-sandwich.jpg", emoji: "🥪", rating: 4, ingredients: ["Sourdough bread", "Grilled zucchini", "Bell peppers", "Herbed cream cheese", "Rocket"], dietaryInfo: ["Vegetarian"], allergens: ["Gluten", "Dairy"], preparationTime: "8 min", calories: 380, featured: true },
      { id: "club-sandwich", name: "Club Sandwich", description: "Triple-decker with fresh veggies, cheese and tangy mayo.", price: 250, category: "Sandwich", image: "/clients/bake/veg-sandwich.jpg", emoji: "🥪", rating: 5 },
      { id: "croissant", name: "Butter Croissant", description: "Flaky, buttery French croissant baked fresh every morning.", price: 140, category: "Pastry", image: "/clients/bake/croissant.jpg", emoji: "🥐", rating: 5, ingredients: ["Flour", "French butter", "Yeast", "Sea salt"], dietaryInfo: ["Vegetarian"], allergens: ["Gluten", "Dairy", "Egg"], calories: 270, featured: true },
      { id: "danish", name: "Fruit Danish", description: "Light pastry layered with custard and seasonal fruit.", price: 150, category: "Pastry", image: "/clients/bake/croissant.jpg", emoji: "🥐", rating: 4 },
      { id: "chocolate-cake", name: "Chocolate Cake", description: "Decadent triple-layer chocolate cake with ganache.", price: 180, category: "Cake", image: "/clients/bake/chocolate-cake.jpg", emoji: "🍰", rating: 5, ingredients: ["Dark chocolate", "Cocoa", "Butter", "Eggs", "Ganache"], dietaryInfo: ["Vegetarian"], allergens: ["Gluten", "Dairy", "Egg"], calories: 420 },
      { id: "cheesecake", name: "Classic Cheesecake", description: "Creamy baked cheesecake on a crunchy biscuit base.", price: 210, category: "Cake", image: "/clients/bake/chocolate-cake.jpg", emoji: "🍰", rating: 5 },
      { id: "cookie", name: "Choco-Chip Cookie", description: "Warm, chewy cookie loaded with Belgian chocolate chips.", price: 100, category: "Cookie", image: "/clients/bake/cookie.jpg", emoji: "🍪", rating: 4, ingredients: ["Butter", "Brown sugar", "Belgian chocolate chips", "Flour"], allergens: ["Gluten", "Dairy"], preparationTime: "Baked fresh daily" },
      { id: "oat-cookie", name: "Oatmeal Cookie", description: "Hearty oats and raisins baked golden and chewy.", price: 90, category: "Cookie", image: "/clients/bake/cookie.jpg", emoji: "🍪", rating: 4 },
    ],
    reviewSettings: {
      shareTitle: "Share Your Experience",
      shareSubtitle: "Help us grow with your valuable review",
    },
  },
  {
    id: "client_sharma_cafe",
    source: "local",
    slug: "sharma-cafe",
    businessName: "Sharma Cafe",
    displayName: "SHARMA",
    displaySubtitle: "CHAI & CAFE",
    logo: "/clients/sharma-cafe/logo.svg",
    favicon: "/clients/sharma-cafe/logo.svg",
    tagline: "Garma Garam Chai, Dil Se",
    description: "Kulhad chai, hot snacks and warm smiles. Share your Sharma Cafe experience.",
    currency: "₹",
    theme: {
      primary: "#7a1f2b",
      primaryDark: "#5a1520",
      secondary: "#fbe9dc",
      accent: "#f08a24",
      onAccent: "#3a0d12",
      background: "#fff6ef",
      surface: "#fffbf7",
      text: "#5a1520",
      muted: "#9a6b63",
      borderRadius: "1.25rem",
    },
    coverImage: "/clients/sharma-cafe/cover.jpg",
    googleReviewUrl: "https://search.google.com/local/writereview?placeid=demo-sharma-cafe",
    socialLinks: {
      instagram: "https://www.instagram.com/sharmacafe.demo",
      facebook: "https://www.facebook.com/sharmacafe.demo",
    },
    wifi: { enabled: true, ssid: "SHARMA_FREE_WIFI", hint: "Free Wi-Fi with every cup of chai!" },
    loyalty: { enabled: true, stampTarget: 10, rewardName: "Free Masala Chai" },
    aiReview: { enabled: true, monthlyLimit: 200 },
    menu: [
      { id: "masala-chai", name: "Masala Chai", description: "Kulhad chai brewed with ginger, cardamom and spices.", price: 30, category: "Chai", image: "/clients/sharma-cafe/masala-chai.jpg", emoji: "🍵", rating: 5, ingredients: ["Assam tea", "Milk", "Ginger", "Cardamom", "Cinnamon"], dietaryInfo: ["Vegetarian"], allergens: ["Dairy"], preparationTime: "6 min", featured: true },
      { id: "elaichi-chai", name: "Elaichi Chai", description: "Fragrant cardamom tea, slow-boiled the classic way.", price: 30, category: "Chai", image: "/clients/sharma-cafe/masala-chai.jpg", emoji: "🍵", rating: 5 },
      { id: "filter-coffee", name: "Filter Coffee", description: "South Indian decoction coffee with frothy milk.", price: 50, category: "Coffee", emoji: "☕", rating: 4 },
      { id: "samosa", name: "Punjabi Samosa", description: "Crispy pastry stuffed with spiced potato and peas.", price: 25, category: "Snacks", image: "/clients/sharma-cafe/samosa.jpg", emoji: "🥟", rating: 5, ingredients: ["Potato", "Green peas", "Spices", "Pastry"], dietaryInfo: ["Vegetarian", "Vegan"], allergens: ["Gluten"], preparationTime: "5 min", featured: true },
      { id: "bun-maska", name: "Bun Maska", description: "Soft bun slathered with butter — the perfect chai partner.", price: 40, category: "Snacks", emoji: "🍞", rating: 4 },
      { id: "paneer-sandwich", name: "Paneer Tikka Sandwich", description: "Grilled sandwich with smoky paneer tikka and mint chutney.", price: 90, category: "Sandwich", emoji: "🥪", rating: 4 },
      { id: "bombay-sandwich", name: "Bombay Masala Sandwich", description: "Layers of veggies, chutney and masala, toasted golden.", price: 70, category: "Sandwich", emoji: "🥪", rating: 4 },
      { id: "gajar-halwa", name: "Gajar Halwa", description: "Slow-cooked carrot pudding with ghee and dry fruits.", price: 60, category: "Dessert", emoji: "🥕", rating: 5 },
    ],
    reviewSettings: {
      shareTitle: "Kaisa Laga Aapko?",
      shareSubtitle: "Tell us about your chai experience",
    },
  },
  {
    id: "client_royal_restaurant",
    source: "local",
    slug: "royal-restaurant",
    businessName: "Royal Restaurant",
    displayName: "ROYAL",
    displaySubtitle: "FINE DINING",
    logo: "/clients/royal-restaurant/logo.svg",
    favicon: "/clients/royal-restaurant/logo.svg",
    tagline: "A Feast Fit for Royalty",
    description: "Classic Indian fine dining. Tell us about your royal dining experience.",
    currency: "₹",
    theme: {
      primary: "#1f3b36",
      primaryDark: "#142a26",
      secondary: "#e7eee8",
      accent: "#c9a227",
      onAccent: "#1a1505",
      background: "#f4f6f1",
      surface: "#ffffff",
      text: "#1f3b36",
      muted: "#5f7570",
      borderRadius: "0.75rem",
    },
    coverImage: "/clients/royal-restaurant/cover.jpg",
    googleReviewUrl: "https://search.google.com/local/writereview?placeid=demo-royal-restaurant",
    socialLinks: {
      instagram: "https://www.instagram.com/royalrestaurant.demo",
      youtube: "https://www.youtube.com/@royalrestaurant.demo",
      website: "https://royal-restaurant.example.com",
    },
    wifi: { enabled: false },
    loyalty: { enabled: true, stampTarget: 6, rewardName: "Free Dessert" },
    aiReview: { enabled: true, monthlyLimit: 500 },
    menuCategories: ["Starters", "Main Course", "Breads", "Desserts", "Beverages"],
    menu: [
      { id: "paneer-tikka", name: "Paneer Tikka", description: "Cottage cheese marinated in spices, charred in the tandoor.", price: 320, category: "Starters", image: "/clients/royal-restaurant/paneer.jpg", emoji: "🍢", rating: 5, ingredients: ["Paneer", "Yoghurt marinade", "Bell peppers", "Onion", "Tandoori spices"], dietaryInfo: ["Vegetarian"], allergens: ["Dairy"], preparationTime: "15 min", featured: true },
      { id: "hara-kebab", name: "Hara Bhara Kebab", description: "Spinach and green pea patties with mint chutney.", price: 280, category: "Starters", emoji: "🥬", rating: 4 },
      { id: "biryani", name: "Royal Dum Biryani", description: "Fragrant basmati slow-cooked with saffron and spices.", price: 450, category: "Main Course", image: "/clients/royal-restaurant/biryani.jpg", emoji: "🍛", rating: 5, ingredients: ["Basmati rice", "Saffron", "Fried onions", "Mint", "Whole spices"], allergens: ["Dairy"], preparationTime: "25 min", calories: 650, featured: true },
      { id: "dal-makhani", name: "Dal Makhani", description: "Black lentils simmered overnight with butter and cream.", price: 340, category: "Main Course", emoji: "🍲", rating: 5 },
      { id: "butter-naan", name: "Butter Naan", description: "Soft tandoor-baked bread brushed with butter.", price: 80, category: "Breads", emoji: "🫓", rating: 4 },
      { id: "gulab-jamun", name: "Gulab Jamun", description: "Warm milk dumplings soaked in rose-cardamom syrup.", price: 160, category: "Desserts", emoji: "🍮", rating: 5, ingredients: ["Khoya", "Rose syrup", "Cardamom", "Pistachio"], dietaryInfo: ["Vegetarian"], allergens: ["Dairy", "Nuts"], calories: 300 },
      { id: "sweet-lassi", name: "Sweet Lassi", description: "Thick chilled yoghurt drink topped with malai.", price: 140, category: "Beverages", emoji: "🥛", rating: 4 },
    ],
    reviewSettings: {
      shareTitle: "Rate Your Royal Feast",
      shareSubtitle: "Your feedback helps us serve you better",
      questionTitles: { experience: "How was your dining experience?" },
    },
  },
];
